name: MineSkyVanish
version: '1.0.0-BETA'

main: net.mineskyvanish.plugin.MineSkyVanish
api-version: '26.1'

load: POSTWORLD

folia-supported: true

softdepend:
  - ProtocolLib
  - Essentials
  - PlaceholderAPI
  - Vault
  - OpenInv
commands:
  msv:
    usage: /vanish
    description: mineskyvanish's main command
    aliases: [mineskyvanish, v, vanish]
permissions:
  mineskyvanish.*:
    children:
      mineskyvanish.use: true
      mineskyvanish.see: true
      mineskyvanish.reload: true
      mineskyvanish.logout: true
      mineskyvanish.login: true
      mineskyvanish.others: true
      mineskyvanish.list: true
      mineskyvanish.keepfly: true
      mineskyvanish.toggleitems: true
      mineskyvanish.recreatefiles: true
      mineskyvanish.notoggle: true
      mineskyvanish.joinvanished: true
      mineskyvanish.notify: true
      mineskyvanish.breakblocks: true
      mineskyvanish.placeblocks: true
      mineskyvanish.damage: true
      mineskyvanish.stacktrace: true
      mineskyvanish.silentchest: true
    description: Grants you all MineSkyVanish permissions
  mineskyvanish.see:
    description: You can see other vanished players
  mineskyvanish.notoggle:
    description: Other players cannot hide/show you if you're online
  mineskyvanish.keepfly:
    description: You can always keep flying when you reappear
  mineskyvanish.joinvanished:
    description: You always join vanished (must be enabled in config)
  mineskyvanish.silentchest:
    description: You can open chests silently